-- Record what database queries ran

-- 29/05/25 Initialisation
create table posts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title character varying not null,
  body text not null,
  img character varying not null,
  date timestamp without time zone not null,
  likes integer null,
  constraint posts_pkey primary key (id)
) TABLESPACE pg_default;

create table contact_forms (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email character varying not null,
  message text not null,
  constraint contact_forms_pkey primary key (id)
) TABLESPACE pg_default;